package com.arauca.domain;

// Generated 6/06/2015 07:49:03 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Contrato generated by hbm2java
 */
@Entity
@Table(name = "contrato", catalog = "mydbtest")
public class Contrato implements java.io.Serializable {

	/**
	 * Serial version.
	 */
	private static final long serialVersionUID = 1L;
	private Integer idContrato;
	private Modalidad modalidad;
	private Estado estado;
	private UnidadEjecutora unidadEjecutora;
	private String numProceso;
	private String vigencia;
	private BigDecimal cuantia;
	private int idUnidadContratacion;
	private String numContrato;
	private int idTipoProceso;
	private String objetoContrato;
	private BigDecimal cuantiaAContratar;
	private Date fechaApertura;
	private Date fechaCierre;
	private Date horaCierre;
	private String lugarCierre;
	private String numAdjudicacion;
	private Date fechaAdjudicacion;
	private BigDecimal montoAdjudicado;
	private String plazoAdjudicado;

	public Contrato() {
	}

	public Contrato(Modalidad modalidad, Estado estado,
			UnidadEjecutora unidadEjecutora, String numProceso,
			String vigencia, BigDecimal cuantia, int idUnidadContratacion,
			String numContrato, int idTipoProceso, String objetoContrato,
			BigDecimal cuantiaAContratar) {
		this.modalidad = modalidad;
		this.estado = estado;
		this.unidadEjecutora = unidadEjecutora;
		this.numProceso = numProceso;
		this.vigencia = vigencia;
		this.cuantia = cuantia;
		this.idUnidadContratacion = idUnidadContratacion;
		this.numContrato = numContrato;
		this.idTipoProceso = idTipoProceso;
		this.objetoContrato = objetoContrato;
		this.cuantiaAContratar = cuantiaAContratar;
	}

	public Contrato(Modalidad modalidad, Estado estado,
			UnidadEjecutora unidadEjecutora, String numProceso,
			String vigencia, BigDecimal cuantia, int idUnidadContratacion,
			String numContrato, int idTipoProceso, String objetoContrato,
			BigDecimal cuantiaAContratar, Date fechaApertura, Date fechaCierre,
			Date horaCierre, String lugarCierre, String numAdjudicacion,
			Date fechaAdjudicacion, BigDecimal montoAdjudicado,
			String plazoAdjudicado) {
		this.modalidad = modalidad;
		this.estado = estado;
		this.unidadEjecutora = unidadEjecutora;
		this.numProceso = numProceso;
		this.vigencia = vigencia;
		this.cuantia = cuantia;
		this.idUnidadContratacion = idUnidadContratacion;
		this.numContrato = numContrato;
		this.idTipoProceso = idTipoProceso;
		this.objetoContrato = objetoContrato;
		this.cuantiaAContratar = cuantiaAContratar;
		this.fechaApertura = fechaApertura;
		this.fechaCierre = fechaCierre;
		this.horaCierre = horaCierre;
		this.lugarCierre = lugarCierre;
		this.numAdjudicacion = numAdjudicacion;
		this.fechaAdjudicacion = fechaAdjudicacion;
		this.montoAdjudicado = montoAdjudicado;
		this.plazoAdjudicado = plazoAdjudicado;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_contrato", unique = true, nullable = false)
	public Integer getIdContrato() {
		return this.idContrato;
	}

	public void setIdContrato(Integer idContrato) {
		this.idContrato = idContrato;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_modalidad", nullable = false)
	public Modalidad getModalidad() {
		return this.modalidad;
	}

	public void setModalidad(Modalidad modalidad) {
		this.modalidad = modalidad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_estado", nullable = false)
	public Estado getEstado() {
		return this.estado;
	}

	public void setEstado(Estado estado) {
		this.estado = estado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_unidad_ejecutora", nullable = false)
	public UnidadEjecutora getUnidadEjecutora() {
		return this.unidadEjecutora;
	}

	public void setUnidadEjecutora(UnidadEjecutora unidadEjecutora) {
		this.unidadEjecutora = unidadEjecutora;
	}

	@Column(name = "num_proceso", nullable = false, length = 45)
	public String getNumProceso() {
		return this.numProceso;
	}

	public void setNumProceso(String numProceso) {
		this.numProceso = numProceso;
	}

	@Column(name = "vigencia", nullable = false, length = 45)
	public String getVigencia() {
		return this.vigencia;
	}

	public void setVigencia(String vigencia) {
		this.vigencia = vigencia;
	}

	@Column(name = "cuantia", nullable = false, precision = 45, scale = 0)
	public BigDecimal getCuantia() {
		return this.cuantia;
	}

	public void setCuantia(BigDecimal cuantia) {
		this.cuantia = cuantia;
	}

	@Column(name = "id_unidad_contratacion", nullable = false)
	public int getIdUnidadContratacion() {
		return this.idUnidadContratacion;
	}

	public void setIdUnidadContratacion(int idUnidadContratacion) {
		this.idUnidadContratacion = idUnidadContratacion;
	}

	@Column(name = "num_contrato", nullable = false, length = 45)
	public String getNumContrato() {
		return this.numContrato;
	}

	public void setNumContrato(String numContrato) {
		this.numContrato = numContrato;
	}

	@Column(name = "id_tipo_proceso", nullable = false)
	public int getIdTipoProceso() {
		return this.idTipoProceso;
	}

	public void setIdTipoProceso(int idTipoProceso) {
		this.idTipoProceso = idTipoProceso;
	}

	@Column(name = "objeto_contrato", nullable = false, length = 250)
	public String getObjetoContrato() {
		return this.objetoContrato;
	}

	public void setObjetoContrato(String objetoContrato) {
		this.objetoContrato = objetoContrato;
	}

	@Column(name = "cuantia_a_contratar", nullable = false, precision = 45, scale = 0)
	public BigDecimal getCuantiaAContratar() {
		return this.cuantiaAContratar;
	}

	public void setCuantiaAContratar(BigDecimal cuantiaAContratar) {
		this.cuantiaAContratar = cuantiaAContratar;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_apertura", length = 19)
	public Date getFechaApertura() {
		return this.fechaApertura;
	}

	public void setFechaApertura(Date fechaApertura) {
		this.fechaApertura = fechaApertura;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_cierre", length = 19)
	public Date getFechaCierre() {
		return this.fechaCierre;
	}

	public void setFechaCierre(Date fechaCierre) {
		this.fechaCierre = fechaCierre;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "hora_cierre", length = 19)
	public Date getHoraCierre() {
		return this.horaCierre;
	}

	public void setHoraCierre(Date horaCierre) {
		this.horaCierre = horaCierre;
	}

	@Column(name = "lugar_cierre", length = 45)
	public String getLugarCierre() {
		return this.lugarCierre;
	}

	public void setLugarCierre(String lugarCierre) {
		this.lugarCierre = lugarCierre;
	}

	@Column(name = "num_adjudicacion", length = 45)
	public String getNumAdjudicacion() {
		return this.numAdjudicacion;
	}

	public void setNumAdjudicacion(String numAdjudicacion) {
		this.numAdjudicacion = numAdjudicacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_adjudicacion", length = 19)
	public Date getFechaAdjudicacion() {
		return this.fechaAdjudicacion;
	}

	public void setFechaAdjudicacion(Date fechaAdjudicacion) {
		this.fechaAdjudicacion = fechaAdjudicacion;
	}

	@Column(name = "monto_adjudicado", precision = 45, scale = 0)
	public BigDecimal getMontoAdjudicado() {
		return this.montoAdjudicado;
	}

	public void setMontoAdjudicado(BigDecimal montoAdjudicado) {
		this.montoAdjudicado = montoAdjudicado;
	}

	@Column(name = "plazo_adjudicado", length = 45)
	public String getPlazoAdjudicado() {
		return this.plazoAdjudicado;
	}

	public void setPlazoAdjudicado(String plazoAdjudicado) {
		this.plazoAdjudicado = plazoAdjudicado;
	}

}
