package com.arauca.domain;

// Generated 6/06/2015 07:49:03 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Dependencia generated by hbm2java
 */
@Entity
@Table(name = "dependencia", catalog = "mydbtest")
public class Dependencia implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idDependencia;
	private String nombreDependencia;
	private String codDependencia;

	public Dependencia() {
	}

	public Dependencia(String nombreDependencia) {
		this.nombreDependencia = nombreDependencia;
	}

	public Dependencia(String nombreDependencia, String codDependencia) {
		this.nombreDependencia = nombreDependencia;
		this.codDependencia = codDependencia;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_dependencia", unique = true, nullable = false)
	public Integer getIdDependencia() {
		return this.idDependencia;
	}

	public void setIdDependencia(Integer idDependencia) {
		this.idDependencia = idDependencia;
	}

	@Column(name = "nombre_dependencia", nullable = false, length = 45)
	public String getNombreDependencia() {
		return this.nombreDependencia;
	}

	public void setNombreDependencia(String nombreDependencia) {
		this.nombreDependencia = nombreDependencia;
	}

	@Column(name = "cod_dependencia", length = 45)
	public String getCodDependencia() {
		return this.codDependencia;
	}

	public void setCodDependencia(String codDependencia) {
		this.codDependencia = codDependencia;
	}

}
