package com.arauca.domain;

// Generated 6/06/2015 07:49:03 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DimensionPdm generated by hbm2java
 */
@Entity
@Table(name = "dimension_pdm", catalog = "mydbtest")
public class DimensionPdm implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idDimensionPdm;
	private String codDimensionPdm;
	private String nombreDimensionPdm;

	public DimensionPdm() {
	}

	public DimensionPdm(int idDimensionPdm, String codDimensionPdm,
			String nombreDimensionPdm) {
		this.idDimensionPdm = idDimensionPdm;
		this.codDimensionPdm = codDimensionPdm;
		this.nombreDimensionPdm = nombreDimensionPdm;
	}

	@Id
	@Column(name = "id_dimension_pdm", unique = true, nullable = false)
	public int getIdDimensionPdm() {
		return this.idDimensionPdm;
	}

	public void setIdDimensionPdm(int idDimensionPdm) {
		this.idDimensionPdm = idDimensionPdm;
	}

	@Column(name = "cod_dimension_pdm", nullable = false, length = 45)
	public String getCodDimensionPdm() {
		return this.codDimensionPdm;
	}

	public void setCodDimensionPdm(String codDimensionPdm) {
		this.codDimensionPdm = codDimensionPdm;
	}

	@Column(name = "nombre_dimension_pdm", nullable = false, length = 45)
	public String getNombreDimensionPdm() {
		return this.nombreDimensionPdm;
	}

	public void setNombreDimensionPdm(String nombreDimensionPdm) {
		this.nombreDimensionPdm = nombreDimensionPdm;
	}

}
