package com.arauca.domain;

// Generated 6/06/2015 07:49:03 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Modalidad generated by hbm2java
 */
@Entity
@Table(name = "modalidad", catalog = "mydbtest")
public class Modalidad implements java.io.Serializable {

	/**
	 * Serial Version UID.
	 */
	private static final long serialVersionUID = 1L;
	private int idModalidad;
	private String nombreModalidad;
	private Set<Contrato> contratos = new HashSet<Contrato>(0);

	public Modalidad() {
	}

	public Modalidad(int idModalidad, String nombreModalidad) {
		this.idModalidad = idModalidad;
		this.nombreModalidad = nombreModalidad;
	}

	public Modalidad(int idModalidad, String nombreModalidad,
			Set<Contrato> contratos) {
		this.idModalidad = idModalidad;
		this.nombreModalidad = nombreModalidad;
		this.contratos = contratos;
	}

	@Id
	@Column(name = "id_modalidad", unique = true, nullable = false)
	public int getIdModalidad() {
		return this.idModalidad;
	}

	public void setIdModalidad(int idModalidad) {
		this.idModalidad = idModalidad;
	}

	@Column(name = "nombre_modalidad", nullable = false, length = 45)
	public String getNombreModalidad() {
		return this.nombreModalidad;
	}

	public void setNombreModalidad(String nombreModalidad) {
		this.nombreModalidad = nombreModalidad;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modalidad")
	public Set<Contrato> getContratos() {
		return this.contratos;
	}

	public void setContratos(Set<Contrato> contratos) {
		this.contratos = contratos;
	}

}
