package com.arauca.domain;

// Generated 6/06/2015 07:49:03 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ProgramaPdm generated by hbm2java
 */
@Entity
@Table(name = "programa_pdm", catalog = "mydbtest")
public class ProgramaPdm implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idProgramaPdm;
	private String codProgramaPdm;
	private String nombreProgramaPdm;

	public ProgramaPdm() {
	}

	public ProgramaPdm(String codProgramaPdm, String nombreProgramaPdm) {
		this.codProgramaPdm = codProgramaPdm;
		this.nombreProgramaPdm = nombreProgramaPdm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_programa_pdm", unique = true, nullable = false)
	public Integer getIdProgramaPdm() {
		return this.idProgramaPdm;
	}

	public void setIdProgramaPdm(Integer idProgramaPdm) {
		this.idProgramaPdm = idProgramaPdm;
	}

	@Column(name = "cod_programa_pdm", nullable = false, length = 45)
	public String getCodProgramaPdm() {
		return this.codProgramaPdm;
	}

	public void setCodProgramaPdm(String codProgramaPdm) {
		this.codProgramaPdm = codProgramaPdm;
	}

	@Column(name = "nombre_programa_pdm", nullable = false, length = 45)
	public String getNombreProgramaPdm() {
		return this.nombreProgramaPdm;
	}

	public void setNombreProgramaPdm(String nombreProgramaPdm) {
		this.nombreProgramaPdm = nombreProgramaPdm;
	}

}
