package com.arauca.domain;

// Generated 6/06/2015 07:49:03 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Proyecto generated by hbm2java
 */
@Entity
@Table(name = "proyecto", catalog = "mydbtest")
public class Proyecto implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idProyecto;
	private String codigoBpim;
	private Date fechaRadicacion;
	private Date fechaRegistro;
	private String denominacionProyectoInversion;
	private String objetivoGeneralProyecto;
	private int idEntidadRadica;
	private int idFuncionarioResponsable;
	private int idDimensionPdm;
	private int idSectorInversionPdm;
	private int idProgramaPdm;
	private int idSubprogramaPdm;
	private String codigoRubroPresupuestal;
	private String nombreRubroPresupuestal;
	private int idDependenciaAvalViabilidad;
	private int idFuncionarioExpViabilidad;
	private int idFuncionarioBpControlPosterior;
	private String conceptoControlPosterior;
	private String metaResultadoPdmDesc;
	private String metaResultadoPdmIndic;
	private String metaResultadoPdmLineaBase;
	private String metaResultadoPdmVlrProgramado;
	private String metaProductoPdmDesc;
	private String metaProductoPdmIndic;
	private String metaProductoPdmLineaBase;
	private String metaProductoPdmVlrProgramado;

	public Proyecto() {
	}

	public Proyecto(int idProyecto, String codigoBpim, Date fechaRadicacion,
			Date fechaRegistro, String denominacionProyectoInversion,
			String objetivoGeneralProyecto, int idEntidadRadica,
			int idFuncionarioResponsable, int idDimensionPdm,
			int idSectorInversionPdm, int idProgramaPdm, int idSubprogramaPdm,
			String codigoRubroPresupuestal, String nombreRubroPresupuestal,
			int idDependenciaAvalViabilidad, int idFuncionarioExpViabilidad,
			int idFuncionarioBpControlPosterior,
			String conceptoControlPosterior, String metaResultadoPdmDesc,
			String metaResultadoPdmIndic, String metaResultadoPdmLineaBase,
			String metaResultadoPdmVlrProgramado, String metaProductoPdmDesc,
			String metaProductoPdmIndic, String metaProductoPdmLineaBase,
			String metaProductoPdmVlrProgramado) {
		this.idProyecto = idProyecto;
		this.codigoBpim = codigoBpim;
		this.fechaRadicacion = fechaRadicacion;
		this.fechaRegistro = fechaRegistro;
		this.denominacionProyectoInversion = denominacionProyectoInversion;
		this.objetivoGeneralProyecto = objetivoGeneralProyecto;
		this.idEntidadRadica = idEntidadRadica;
		this.idFuncionarioResponsable = idFuncionarioResponsable;
		this.idDimensionPdm = idDimensionPdm;
		this.idSectorInversionPdm = idSectorInversionPdm;
		this.idProgramaPdm = idProgramaPdm;
		this.idSubprogramaPdm = idSubprogramaPdm;
		this.codigoRubroPresupuestal = codigoRubroPresupuestal;
		this.nombreRubroPresupuestal = nombreRubroPresupuestal;
		this.idDependenciaAvalViabilidad = idDependenciaAvalViabilidad;
		this.idFuncionarioExpViabilidad = idFuncionarioExpViabilidad;
		this.idFuncionarioBpControlPosterior = idFuncionarioBpControlPosterior;
		this.conceptoControlPosterior = conceptoControlPosterior;
		this.metaResultadoPdmDesc = metaResultadoPdmDesc;
		this.metaResultadoPdmIndic = metaResultadoPdmIndic;
		this.metaResultadoPdmLineaBase = metaResultadoPdmLineaBase;
		this.metaResultadoPdmVlrProgramado = metaResultadoPdmVlrProgramado;
		this.metaProductoPdmDesc = metaProductoPdmDesc;
		this.metaProductoPdmIndic = metaProductoPdmIndic;
		this.metaProductoPdmLineaBase = metaProductoPdmLineaBase;
		this.metaProductoPdmVlrProgramado = metaProductoPdmVlrProgramado;
	}

	@Id
	@Column(name = "id_proyecto", unique = true, nullable = false)
	public int getIdProyecto() {
		return this.idProyecto;
	}

	public void setIdProyecto(int idProyecto) {
		this.idProyecto = idProyecto;
	}

	@Column(name = "codigo_bpim", nullable = false, length = 45)
	public String getCodigoBpim() {
		return this.codigoBpim;
	}

	public void setCodigoBpim(String codigoBpim) {
		this.codigoBpim = codigoBpim;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_radicacion", nullable = false, length = 19)
	public Date getFechaRadicacion() {
		return this.fechaRadicacion;
	}

	public void setFechaRadicacion(Date fechaRadicacion) {
		this.fechaRadicacion = fechaRadicacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_registro", nullable = false, length = 19)
	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	@Column(name = "denominacion_proyecto_inversion", nullable = false, length = 250)
	public String getDenominacionProyectoInversion() {
		return this.denominacionProyectoInversion;
	}

	public void setDenominacionProyectoInversion(
			String denominacionProyectoInversion) {
		this.denominacionProyectoInversion = denominacionProyectoInversion;
	}

	@Column(name = "objetivo_general_proyecto", nullable = false, length = 250)
	public String getObjetivoGeneralProyecto() {
		return this.objetivoGeneralProyecto;
	}

	public void setObjetivoGeneralProyecto(String objetivoGeneralProyecto) {
		this.objetivoGeneralProyecto = objetivoGeneralProyecto;
	}

	@Column(name = "id_entidad_radica", nullable = false)
	public int getIdEntidadRadica() {
		return this.idEntidadRadica;
	}

	public void setIdEntidadRadica(int idEntidadRadica) {
		this.idEntidadRadica = idEntidadRadica;
	}

	@Column(name = "id_funcionario_responsable", nullable = false)
	public int getIdFuncionarioResponsable() {
		return this.idFuncionarioResponsable;
	}

	public void setIdFuncionarioResponsable(int idFuncionarioResponsable) {
		this.idFuncionarioResponsable = idFuncionarioResponsable;
	}

	@Column(name = "id_dimension_pdm", nullable = false)
	public int getIdDimensionPdm() {
		return this.idDimensionPdm;
	}

	public void setIdDimensionPdm(int idDimensionPdm) {
		this.idDimensionPdm = idDimensionPdm;
	}

	@Column(name = "id_sector_inversion_pdm", nullable = false)
	public int getIdSectorInversionPdm() {
		return this.idSectorInversionPdm;
	}

	public void setIdSectorInversionPdm(int idSectorInversionPdm) {
		this.idSectorInversionPdm = idSectorInversionPdm;
	}

	@Column(name = "id_programa_pdm", nullable = false)
	public int getIdProgramaPdm() {
		return this.idProgramaPdm;
	}

	public void setIdProgramaPdm(int idProgramaPdm) {
		this.idProgramaPdm = idProgramaPdm;
	}

	@Column(name = "id_subprograma_pdm", nullable = false)
	public int getIdSubprogramaPdm() {
		return this.idSubprogramaPdm;
	}

	public void setIdSubprogramaPdm(int idSubprogramaPdm) {
		this.idSubprogramaPdm = idSubprogramaPdm;
	}

	@Column(name = "codigo_rubro_presupuestal", nullable = false, length = 45)
	public String getCodigoRubroPresupuestal() {
		return this.codigoRubroPresupuestal;
	}

	public void setCodigoRubroPresupuestal(String codigoRubroPresupuestal) {
		this.codigoRubroPresupuestal = codigoRubroPresupuestal;
	}

	@Column(name = "nombre_rubro_presupuestal", nullable = false, length = 45)
	public String getNombreRubroPresupuestal() {
		return this.nombreRubroPresupuestal;
	}

	public void setNombreRubroPresupuestal(String nombreRubroPresupuestal) {
		this.nombreRubroPresupuestal = nombreRubroPresupuestal;
	}

	@Column(name = "id_dependencia_aval_viabilidad", nullable = false)
	public int getIdDependenciaAvalViabilidad() {
		return this.idDependenciaAvalViabilidad;
	}

	public void setIdDependenciaAvalViabilidad(int idDependenciaAvalViabilidad) {
		this.idDependenciaAvalViabilidad = idDependenciaAvalViabilidad;
	}

	@Column(name = "id_funcionario_exp_viabilidad", nullable = false)
	public int getIdFuncionarioExpViabilidad() {
		return this.idFuncionarioExpViabilidad;
	}

	public void setIdFuncionarioExpViabilidad(int idFuncionarioExpViabilidad) {
		this.idFuncionarioExpViabilidad = idFuncionarioExpViabilidad;
	}

	@Column(name = "id_funcionario_bp_control_posterior", nullable = false)
	public int getIdFuncionarioBpControlPosterior() {
		return this.idFuncionarioBpControlPosterior;
	}

	public void setIdFuncionarioBpControlPosterior(
			int idFuncionarioBpControlPosterior) {
		this.idFuncionarioBpControlPosterior = idFuncionarioBpControlPosterior;
	}

	@Column(name = "concepto_control_posterior", nullable = false, length = 250)
	public String getConceptoControlPosterior() {
		return this.conceptoControlPosterior;
	}

	public void setConceptoControlPosterior(String conceptoControlPosterior) {
		this.conceptoControlPosterior = conceptoControlPosterior;
	}

	@Column(name = "meta_resultado_pdm_desc", nullable = false, length = 250)
	public String getMetaResultadoPdmDesc() {
		return this.metaResultadoPdmDesc;
	}

	public void setMetaResultadoPdmDesc(String metaResultadoPdmDesc) {
		this.metaResultadoPdmDesc = metaResultadoPdmDesc;
	}

	@Column(name = "meta_resultado_pdm_indic", nullable = false, length = 250)
	public String getMetaResultadoPdmIndic() {
		return this.metaResultadoPdmIndic;
	}

	public void setMetaResultadoPdmIndic(String metaResultadoPdmIndic) {
		this.metaResultadoPdmIndic = metaResultadoPdmIndic;
	}

	@Column(name = "meta_resultado_pdm_linea_base", nullable = false, length = 45)
	public String getMetaResultadoPdmLineaBase() {
		return this.metaResultadoPdmLineaBase;
	}

	public void setMetaResultadoPdmLineaBase(String metaResultadoPdmLineaBase) {
		this.metaResultadoPdmLineaBase = metaResultadoPdmLineaBase;
	}

	@Column(name = "meta_resultado_pdm_vlr_programado", nullable = false, length = 45)
	public String getMetaResultadoPdmVlrProgramado() {
		return this.metaResultadoPdmVlrProgramado;
	}

	public void setMetaResultadoPdmVlrProgramado(
			String metaResultadoPdmVlrProgramado) {
		this.metaResultadoPdmVlrProgramado = metaResultadoPdmVlrProgramado;
	}

	@Column(name = "meta_producto_pdm_desc", nullable = false, length = 250)
	public String getMetaProductoPdmDesc() {
		return this.metaProductoPdmDesc;
	}

	public void setMetaProductoPdmDesc(String metaProductoPdmDesc) {
		this.metaProductoPdmDesc = metaProductoPdmDesc;
	}

	@Column(name = "meta_producto_pdm_indic", nullable = false, length = 250)
	public String getMetaProductoPdmIndic() {
		return this.metaProductoPdmIndic;
	}

	public void setMetaProductoPdmIndic(String metaProductoPdmIndic) {
		this.metaProductoPdmIndic = metaProductoPdmIndic;
	}

	@Column(name = "meta_producto_pdm_linea_base", nullable = false, length = 45)
	public String getMetaProductoPdmLineaBase() {
		return this.metaProductoPdmLineaBase;
	}

	public void setMetaProductoPdmLineaBase(String metaProductoPdmLineaBase) {
		this.metaProductoPdmLineaBase = metaProductoPdmLineaBase;
	}

	@Column(name = "meta_producto_pdm_vlr_programado", nullable = false, length = 45)
	public String getMetaProductoPdmVlrProgramado() {
		return this.metaProductoPdmVlrProgramado;
	}

	public void setMetaProductoPdmVlrProgramado(
			String metaProductoPdmVlrProgramado) {
		this.metaProductoPdmVlrProgramado = metaProductoPdmVlrProgramado;
	}

}
