package com.arauca.domain;

// Generated 6/06/2015 07:49:03 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SectorInversionPdm generated by hbm2java
 */
@Entity
@Table(name = "sector_inversion_pdm", catalog = "mydbtest")
public class SectorInversionPdm implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idSectorInversionPdm;
	private String codSectorInversionPdm;
	private String nombreSectorInversionPdm;

	public SectorInversionPdm() {
	}

	public SectorInversionPdm(String codSectorInversionPdm,
			String nombreSectorInversionPdm) {
		this.codSectorInversionPdm = codSectorInversionPdm;
		this.nombreSectorInversionPdm = nombreSectorInversionPdm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_sector_inversion_pdm", unique = true, nullable = false)
	public Integer getIdSectorInversionPdm() {
		return this.idSectorInversionPdm;
	}

	public void setIdSectorInversionPdm(Integer idSectorInversionPdm) {
		this.idSectorInversionPdm = idSectorInversionPdm;
	}

	@Column(name = "cod_sector_inversion_pdm", nullable = false, length = 45)
	public String getCodSectorInversionPdm() {
		return this.codSectorInversionPdm;
	}

	public void setCodSectorInversionPdm(String codSectorInversionPdm) {
		this.codSectorInversionPdm = codSectorInversionPdm;
	}

	@Column(name = "nombre_sector_inversion_pdm", nullable = false, length = 45)
	public String getNombreSectorInversionPdm() {
		return this.nombreSectorInversionPdm;
	}

	public void setNombreSectorInversionPdm(String nombreSectorInversionPdm) {
		this.nombreSectorInversionPdm = nombreSectorInversionPdm;
	}

}
