package com.arauca.domain;

// Generated 6/06/2015 07:49:03 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SubprogramaPdm generated by hbm2java
 */
@Entity
@Table(name = "subprograma_pdm", catalog = "mydbtest")
public class SubprogramaPdm implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idSubprogramaPdm;
	private int idProgramaPdm;
	private String codSubprogramaPdm;
	private String nombreSubprogramaPdm;

	public SubprogramaPdm() {
	}

	public SubprogramaPdm(int idProgramaPdm, String codSubprogramaPdm,
			String nombreSubprogramaPdm) {
		this.idProgramaPdm = idProgramaPdm;
		this.codSubprogramaPdm = codSubprogramaPdm;
		this.nombreSubprogramaPdm = nombreSubprogramaPdm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_subprograma_pdm", unique = true, nullable = false)
	public Integer getIdSubprogramaPdm() {
		return this.idSubprogramaPdm;
	}

	public void setIdSubprogramaPdm(Integer idSubprogramaPdm) {
		this.idSubprogramaPdm = idSubprogramaPdm;
	}

	@Column(name = "id_programa_pdm", nullable = false)
	public int getIdProgramaPdm() {
		return this.idProgramaPdm;
	}

	public void setIdProgramaPdm(int idProgramaPdm) {
		this.idProgramaPdm = idProgramaPdm;
	}

	@Column(name = "cod_subprograma_pdm", nullable = false, length = 45)
	public String getCodSubprogramaPdm() {
		return this.codSubprogramaPdm;
	}

	public void setCodSubprogramaPdm(String codSubprogramaPdm) {
		this.codSubprogramaPdm = codSubprogramaPdm;
	}

	@Column(name = "nombre_subprograma_pdm", nullable = false, length = 45)
	public String getNombreSubprogramaPdm() {
		return this.nombreSubprogramaPdm;
	}

	public void setNombreSubprogramaPdm(String nombreSubprogramaPdm) {
		this.nombreSubprogramaPdm = nombreSubprogramaPdm;
	}

}
