package com.arauca.domain;

// Generated 6/06/2015 07:49:03 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UnidadEjecutora generated by hbm2java
 */
@Entity
@Table(name = "unidad_ejecutora", catalog = "mydbtest")
public class UnidadEjecutora implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idUnidadEjecutora;
	private String nombreUnidadEjecutora;
	private Set<Contrato> contratos = new HashSet<Contrato>(0);

	public UnidadEjecutora() {
	}

	public UnidadEjecutora(int idUnidadEjecutora, String nombreUnidadEjecutora) {
		this.idUnidadEjecutora = idUnidadEjecutora;
		this.nombreUnidadEjecutora = nombreUnidadEjecutora;
	}

	public UnidadEjecutora(int idUnidadEjecutora, String nombreUnidadEjecutora,
			Set<Contrato> contratos) {
		this.idUnidadEjecutora = idUnidadEjecutora;
		this.nombreUnidadEjecutora = nombreUnidadEjecutora;
		this.contratos = contratos;
	}

	@Id
	@Column(name = "id_unidad_ejecutora", unique = true, nullable = false)
	public int getIdUnidadEjecutora() {
		return this.idUnidadEjecutora;
	}

	public void setIdUnidadEjecutora(int idUnidadEjecutora) {
		this.idUnidadEjecutora = idUnidadEjecutora;
	}

	
	@Column(name = "nombre_unidad_ejecutora", nullable = false, length = 45)
	public String getNombreUnidadEjecutora() {
		return this.nombreUnidadEjecutora;
	}

	public void setNombreUnidadEjecutora(String nombreUnidadEjecutora) {
		this.nombreUnidadEjecutora = nombreUnidadEjecutora;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "unidadEjecutora")
	public Set<Contrato> getContratos() {
		return this.contratos;
	}

	public void setContratos(Set<Contrato> contratos) {
		this.contratos = contratos;
	}

}
